### ISSUE TITLE
Active Link to Bad Rules Info on DTDB.co

### ISSUE THREAD

**Issue by shosuro006** [townteki/dtdb#32]
https://dtdb.co/en/extraRules
Above link used to be part of dtdb.co for old rules concerning totems and kungfu.
It looks like the option to navigate direct to this menu was removed, which is good, however the data on the page is still live?
Anyone with a link can still view the info.

Since this is on a reddit post somewhere in the internet, might be a good idea to kill this specific page, so people dont get confused by the bad info.

It was brought up in the PBE discord yesterday.

**Comment by stopfstedt** [comment]
agreed. will remove this page without replacement.
