### ISSUE TITLE
Deckbuilder: search results linked to wrong card

### ISSUE THREAD

**Issue by stopfstedt** [townteki/dtdb#7]
This search result should link to Allie Hensman (WWE)

![image](https://user-images.githubusercontent.com/1410427/150621184-dd1f6eba-be6a-4c7b-a014-bfaf25477710.png)

However, it links to Allie Hensman (Core)

![image](https://user-images.githubusercontent.com/1410427/150621223-84c86216-c038-46ab-af75-ca2f4377ba0d.png)

This bug only manifests itself for cards that have multiples by title  - the first version (in this case, the Core version of Allie) is linked to by all cards with that title.

Fix this.

**Comment by mmeldo** [comment]
fixed by #10
